plan(10);
my @a;
my %a;
sub null($a, $msg) { ok($a.HOW.name($a) eq 'VMNull', $msg)  };
null( @a-[0], 'unexistent @a-[0]');
null( %a-<0>, 'unexitent %a-<0>');
null( %a-{"0"}, 'unexistent %a-{"0"}');
nqp::push(@a, 42);
ok(@a-[0] == 42, '@a-[0]');
%a<0> := 42;
ok(%a-<0> == 42, '%a-<0>]');
ok(%a-{"0"} == 42, '%a-{"0"}');
ok(@a[0] :exists, '@a[0] :exists');
ok(@a-[0] :exists, '@a-[0] :exists');
%a-<0> :delete;
ok(!%a-<0> :exists, '!%a-<0> :exists');
%a<0> := 42;
%a-{"0"} :delete;
ok(!%a-{"0"} :exists,  '!%a-{"0"} :exists');
